#!!!IMPORTANT: explicitly declare the types implementing NodeInterface in config/packages/graphql.yaml,
#because they won't be autodiscovered
Event:
    type: object
    config:
        interfaces: [NodeInterface]
        fields:
            id:
                type: ID!
            version:
                type: String!
            key:
                type: String!
            name:
                type: String!
            date:
                type: DateTime!
            participants:
                type: "[String!]!"
                args:
                    queryString:
                        type: String
            program:
                type: "[Speech!]!"
                args:
                    sortByStartTime:
                        type: SortDirection
        resolveField: '@=resolver("App\\GraphQL\\Resolver\\EventResolver", [info, value, args, context])'
